from __future__ import annotations

from typing import TypedDict

from langgraph.graph import END, START, StateGraph

from docguard.adapters.agents import AgentGateway
from docguard.domain.models import AuditTask, EvidenceRef, Finding
from docguard.services.reporting import render_markdown


class AuditState(TypedDict, total=False):
    task: AuditTask
    evidence: list[EvidenceRef]
    text_findings: list[Finding]
    architecture_findings: list[Finding]
    findings: list[Finding]
    report_markdown: str


def _preprocess(state: AuditState) -> dict:
    """Placeholder for DOCX acceptance, extraction, rendering and manifest creation."""
    task = state["task"]
    # In production this is generated by the deterministic DOCX pipeline and stored externally.
    evidence = [
        EvidenceRef(
            evidence_id="meta_001",
            kind="metadata",
            source_uri=task.document.source_uri,
            location="document",
            sha256=task.document.content_sha256,
            excerpt=f"Accepted-revision audit package for {task.document.filename}",
        )
    ]
    return {"evidence": evidence}


def _merge_findings(state: AuditState) -> dict:
    # Deterministic root-cause de-duplication: first finding wins for a root-cause key.
    merged: dict[str, Finding] = {}
    for finding in state.get("text_findings", []) + state.get("architecture_findings", []):
        merged.setdefault(finding.root_cause_key, finding)
    return {"findings": list(merged.values())}


def _validate_contract(state: AuditState) -> dict:
    valid_evidence_ids = {item.evidence_id for item in state["evidence"]}
    for finding in state.get("findings", []):
        unknown = set(finding.evidence_ids) - valid_evidence_ids
        if unknown:
            raise ValueError(f"{finding.finding_id} refers to unknown evidence: {sorted(unknown)}")
    return {}


def build_audit_graph(gateway: AgentGateway):
    graph = StateGraph(AuditState)
    graph.add_node("preprocess", _preprocess)
    graph.add_node(
        "full_text_audit",
        lambda state: {"text_findings": gateway.audit_full_text(state["task"].profile, state["evidence"])},
    )
    # graph.add_node(
    #     "architecture_audit",
    #     lambda state: {
    #         "architecture_findings": gateway.audit_architecture(state["task"].profile, state["evidence"])
    #     },
    # )
    # graph.add_node("merge", _merge_findings)
    # graph.add_node("validate", _validate_contract)
    graph.add_node(
        "render",
        lambda state: {"report_markdown": render_markdown(state["task"].profile, state["findings"])},
    )
    graph.add_edge(START, "preprocess")
    graph.add_edge("preprocess", "full_text_audit")
    # graph.add_edge("full_text_audit", "architecture_audit")
    # graph.add_edge("architecture_audit", "merge")
    # graph.add_edge("merge", "validate")
    graph.add_edge("full_text_audit", "render")
    graph.add_edge("render", END)
    return graph.compile()
